version: '3.8'

services:
  solid-api:
    container_name: solid-api
    image: node:lts-alpine
    networks:
      solid-api-network:
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: sh -c "yarn && yarn dev"
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - solid-api-db

  solid-api-bd:
    container_name: solid-api-db
    image: 'postgres:14-alpine'
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}

networks:
  solid-api-network:
    name: solid-api-network